### ISSUE TITLE
How would I convert an object?

### ISSUE THREAD

**Issue by jnc-nj** [EuAndreh/cl-BSON#2]
Is there a way to define methods to convert instances of user-defined classes?

For example, `https://github.com/Rudolph-Miller/jonathan` allows one to define %to-json methods that add to the encoder/decoder.

**Comment by EuAndreh** [comment]
Current implementation focused towards the [`<document>` class](https://github.com/EuAndreh/cl-BSON/blob/4854aa9d64beaedeb1c2d0af16ec3ffe69447829/src/types.lisp#L322-L328).

So maybe you want to convert the user-defined class to a `<document>` and use `#'encode`, or maybe the lib could do it directly.

Patches welcome :)
